{
  "openapi": "3.0.0",
  "x-stoplight": {
    "id": "ztf2v5ejz8sq9"
  },
  "info": {
    "title": "book-store-services",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/user/{userId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "Id of an existing user."
        }
      ],
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Get User Alice Smith": {
                    "value": {
                      "id": 142,
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          }
        },
        "operationId": "get-users-userId",
        "description": "Retrieve the information of the user with the matching user ID."
      },
      "patch": {
        "summary": "Update User Information",
        "operationId": "patch-users-userId",
        "responses": {
          "200": {
            "description": "User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Updated User Rebecca Baker": {
                    "value": {
                      "id": 13,
                      "firstName": "Rebecca",
                      "lastName": "Baker",
                      "email": "rebecca@gmail.com",
                      "dateOfBirth": "1985-10-02",
                      "emailVerified": false,
                      "createDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "description": "Update the information of an existing user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "description": "If a new email is given, the user's email verified property will be set to false."
                  },
                  "dateOfBirth": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Update First Name": {
                  "value": {
                    "firstName": "Rebecca"
                  }
                },
                "Update Email": {
                  "value": {
                    "email": "rebecca@gmail.com"
                  }
                },
                "Update Last Name & Date of Birth": {
                  "value": {
                    "lastName": "Baker",
                    "dateOfBirth": "1985-10-02"
                  }
                }
              }
            }
          },
          "description": "Patch user properties to update."
        }
      }
    },
    "/user": {
      "post": {
        "summary": "Create New User",
        "operationId": "post-user",
        "responses": {
          "200": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "nullable": true
                },
                "examples": {
                  "New User Bob Fellow": {
                    "value": {
                      "id": 12,
                      "firstName": "Bob",
                      "lastName": "Fellow",
                      "email": "bob.fellow@gmail.com",
                      "dateOfBirth": "1996-08-24",
                      "emailVerified": false,
                      "createDate": "2020-11-18"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "dateOfBirth"
                ]
              },
              "examples": {
                "Create User Bob Fellow": {
                  "value": {
                    "firstName": "Bob",
                    "lastName": "Fellow",
                    "email": "bob.fellow@gmail.com",
                    "dateOfBirth": "1996-08-24"
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new user."
        },
        "description": "Create a new user."
      }
    },
    "/book/search/{bookType}": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ListOfBooks"
                }
              }
            }
          }
        },
        "operationId": "get-book-search",
        "description": "Get List of books as per their type"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "bookType",
          "in": "path",
          "required": true
        }
      ]
    },
    "/book/search/id/{bookId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "bookId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookDetails"
                }
              }
            }
          }
        },
        "operationId": "get-book-search-bookId",
        "description": "Get book details"
      }
    },
    "/book/purchase/{bookId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "bookId",
          "in": "path",
          "required": true
        }
      ],
      "post": {
        "summary": "",
        "operationId": "post-book-purchase-bookId",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PurchaseResponse"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PurchaseRequest"
              }
            }
          }
        }
      }
    },
    "/admin/book/add": {
      "patch": {
        "summary": "",
        "operationId": "patch-admin-book-add",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "summary": "",
        "operationId": "post-admin-book-add",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/admin/book/remove/{bookId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "bookId",
          "in": "path",
          "required": true
        }
      ],
      "delete": {
        "summary": "",
        "operationId": "delete-admin-book-remove-bookId",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "BookDetails": {
        "title": "BookDetails",
        "x-stoplight": {
          "id": "dw6m0bx994753"
        },
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "pages": {
            "type": "number"
          },
          "price": {
            "type": "string"
          }
        }
      },
      "ListOfBooks": {
        "title": "ListOfBooks",
        "x-stoplight": {
          "id": "m9265hz0c4xl5"
        },
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/BookDetails"
        }
      },
      "User": {
        "title": "User",
        "x-stoplight": {
          "id": "eic7vyujluz5o"
        },
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "dateOfBirth": {
            "type": "string"
          },
          "createDate": {
            "type": "string"
          }
        },
        "required": [
          "firstName",
          "lastName",
          "email",
          "dateOfBirth"
        ]
      },
      "PurchaseResponse": {
        "title": "PurchaseResponse",
        "x-stoplight": {
          "id": "bqcyf78fjklfr"
        },
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          }
        }
      },
      "PurchaseRequest": {
        "title": "PurchaseRequest",
        "x-stoplight": {
          "id": "5knkqqf5on8nw"
        },
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "credential1": {
            "type": "string"
          },
          "credential2": {
            "type": "string"
          },
          "amount": {
            "type": "string"
          }
        }
      }
    }
  }
}